name: Manual Sync

on:
  workflow_dispatch:
    inputs:
      camu_token:
        description: 'Paste MyCamu Token'
        required: true
        type: string

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: node sync.js
        env:
          CAMU_TOKEN: ${{ github.event.inputs.camu_token }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
